spring.application.name=inventory

# Force H2 to use a fixed name for the in-memory database
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable the H2 web console so we can look at the database through the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Shows the SQL commands generated in the terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true