spring.application.name=inventory

# Neon PostgreSQL Cloud Connection Configuration
spring.datasource.url=jdbc:postgresql://ep-late-fog-a2cixqzd.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_z2HNwo4jPYpD
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate DDL Strategy
# 'update' crystalizes structural changes without truncating existing data
spring.jpa.hibernate.ddl-auto=update

# SQL Logging & Debugging Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true